version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wwwolima_yerbalito
      MYSQL_USER: root
      MYSQL_PASSWORD: rjW63u0I6n
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
